version: '3'

services:
  openldap:
    image: ranvier/openldap:latest
    build: ./openldap

    container_name: openldap
    restart: always

    environment:
      - ORG_NAME="Ranvier"
      - ORG_DNS="example.com"
      - ORG_DN="dc=example,dc=com"
      - SERVER_FQDN="ldap.example.com"
      - ROOT_SECRET="password"
    ports:
      - '389:389'
      - '636:636'
    volumes:
      - '/srv/ldap/config:/config'
      - '/srv/ldap/db:/var/lib/ldap'
