version: '3'

services:
  openldap:
    image: ranvier/openldap:latest
    build: ./openldap

    container_name: openldap
    restart: always

    environment:
      - ORG_NAME=LAB
      - ORG_DNS=LAB.com
      - ORG_DN=dc=LAB,dc=com
      - SERVER_FQDN=ldap.LAB.com
      - ROOT_SECRET=admin
    ports:
      - '389:389'
      - '636:636'
    volumes:
      - './ldap/config:/config'
      - './ldap/db:/var/lib/ldap'
